#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/library
#  jpa:
#    show-ddl: true
#    hibernate:
#      ddl-auto: update
#server:
#  port: 8090

# yml or yaml
# jpg jpeg
# ppt pptx
# doc docx

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Ov23liTbbXkzZaaFkhll
            clientSecret: d955e86f0148d76b2f0bcee86787322e3486df9f
#          facebook:
#            clientId:
#            clientSecret:
#          instagram:
logging:
  level:
    root: debug